// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrqBMd_vYwBbgyAC8eOq_cflfl2CLQsV4',
    appId: '1:693186220801:web:cd3bd186672a3c1a57c100',
    messagingSenderId: '693186220801',
    projectId: 'society-manager-server',
    authDomain: 'society-manager-server.firebaseapp.com',
    storageBucket: 'society-manager-server.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi4bqpC2qgg7lDjjcx_YQNVa-pPFiwK_k',
    appId: '1:693186220801:android:d5f59e1312540c7257c100',
    messagingSenderId: '693186220801',
    projectId: 'society-manager-server',
    storageBucket: 'society-manager-server.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv6MnnFm3swdbynjdTRa_orr-ASxsmsm8',
    appId: '1:693186220801:ios:1ca82a596ff9a2e357c100',
    messagingSenderId: '693186220801',
    projectId: 'society-manager-server',
    storageBucket: 'society-manager-server.firebasestorage.app',
    iosBundleId: 'com.app.societymanager.societyManager',
  );
}
